### ISSUE TITLE
Video Recording of Session

### ISSUE THREAD

**Issue by dmitrizagidulin** [xr3ngine/xr3ngine#223]
Goal: A video capture solution to record the scene.

Demo use. Record capture of Web AR Back camera with Volumetric Assets

* Look into: https://github.com/jbaicoianu/threecap
* Look into: https://github.com/spite/ccapture.js/

**Comment by mrhegemon** [comment]
Proposed plan and possible solutions: (Tasks for Vyacheslav next week from 15 to 20 of June)
Version 1
	Use EffectComposer to place video data to render result ~ 2-3 hrs for R&D
Version 2
	Place Plane object with video texture and align it to camera so it will match ~ 4 
hrs for R&D

Task 1C: Audio Sync for Volumetric Player (#224) (Maksym will do research - no longer valid since another dev is working on it)

Possible solution to calculate current playback speed for both playes - audio and volumetric, then try to balance speed for both ~ 2 hrs for research
(for example use .ontimeupdate on audio player to get current time, get last 3 or 10 updates values and real time used, then calculate average)

**Comment by mrhegemon** [comment]
We want to rebuild the scene recorder as an ECSY component + system to do video capture of our canvas. The creator of threecap has suggested that canvas capture might work better than threecap, but that threecap should still work (and there’s a PR to update to latest three)
