### ISSUE TITLE
Enable / Disable Mic and Video

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#301]
RIght now, when the player joins the call, we want them to start receiving streams, but we don't want them to send any.

When the user presses "video", they will be prompted for camera permission and video will start sending.

When the user preses "mic", they will be prompted for audio permission and audio will start sending.

It's a weird UX since we've grown used to joining the video call and then muting our mic, but for this app most people want to be able to express but need to turn off their mic to prevent total chaos. We are assuming that most people will walk around with their video on freely, but will turn on and off the mic when they want to speak to nearby people.

**Comment by shawticus** [comment]
@tanya-vykliuk Adding you to this task. We will need to review with @barankyle as some of the functionality for this may already be present. I will wait for him to comment.

**Comment by barankyle** [comment]
There's already self-muting present in client/components/ui/PartyParticpantWindow/index.tsx, which should give an good idea of how to do it elsewhere. Specifically, the function in there [toggleAudio](https://github.com/xr3ngine/xr3ngine/blob/dev/packages/client/components/ui/PartyParticipantWindow/index.tsx#L193), around line 193, shows how it's done - look at the clause for 'if (peerId === 'me_cam')', which is the case for the user's audio stream.

Basically, you toggle the audio paused state in MediaStreamComponent, which returns what the new paused status is. Then you call either pauseProducer or resumeProducer from WebRTCFunctions on MediaStreamComponent.instance.camAudioProducer, which is the audio feed from the user's cam (as opposed to the audio feed from a screenshare source, or the audio feed from a consumer of someone else's feed).

This was built assuming that the user's cam feed was already up and running, though, since this window is generated from an existing producer. If people can mute themselves when they're not on a call, there'll have to be some additional logic (likely not very much) to have the PartyParticipantWindow check whether the audio is already paused.

**Comment by barankyle** [comment]
Implemented with #732
