### ISSUE TITLE
Feedback on graphql-sequelize-generator

### ISSUE THREAD

**Issue by vincentdesmares** [xr3ngine/xr3ngine#471]
Hi,

I'm the creator of graphql-sequelize-generator and I wanted to have your feedback on it.

What are you main problems with it?

What would make it easier to use for you?

What was not clear or missing in the [documentation](https://vincent-desmares.gitbook.io/graphql-sequelize-generator/)?

Thank you!

**Comment by shawticus** [comment]
Tagging @barankyle , who implemented subscriptions.

To be honest, we aren't using it a lot yet, but the fact that it works kind of automatically is magic -- right now we're just using it to load scenes from our database. Our initial goal, and a point of R&D we'd like to try in the future, is to replace our websocket signaling with "connection" subscriptions, since we have users joining and leaving every few minutes and it'd be a fairly handy way to shorten the state retrieval loop.

Regarding your plugin-- I think that combined with Feathers.js, it's like a superpower. If the JS community understood GraphQL better I think the Feathers + Sequelize + Apollo + GraphQL Sequelize stack would catch on like wildfire. If you could integrate it into their CLI I think you'd have a really strong competitor to products like Gatsby and Hasura, where the designer really just thinks about the database and the front end and the middle kind of fills in like magic.
